### ISSUE TITLE
Failed validation exists with 0

### ISSUE THREAD

**Issue by llauner** [openAIP/openaip-openair-parser#16]
A failed validation of an openair file exists with an exit code of 0 when it should exit with 1
This would help integrate an automated validation in a github workflow for instance

**Comment by reskume** [comment]
I'm currently looking into this any I'm trying to understand the exact use case here. The current parser behavior is to throw a validation error and give information on the found (mostly geometry related) issues, if one or more airspaces are invalid. To have this behavior, the config parameters must be set the following: 

- validateGeometry: true
- fixGeometry: false

From what I understand this is wht you are looking for or did I get it wrong? If so, can you explain your exact use-case / what you are trying to achieve?

**Comment by llauner** [comment]
Hi
I'm using the program inside a github action (shell script) to validate the change that has just been pushed inside an airspace file.
Currently I'm doing this:
node ./cli.js -f ../france.txt -V -o delete_me.geojson

Regardless of the validation success or error, the program ends with the exit code 0.
So I can't just just check for $? in order to find out if the validation was ok or not: I have to check the output for a the keyword "Error" in order to find out if the validation was successful or not.

It would be better if the program exit code was following the convention of returning 0 if successful, and a value >0 if not.

**Comment by reskume** [comment]
I adjusted the CLI script accordingly. Should now work for your use-case. Fixed in v1.10.0.

**Comment by reskume** [comment]
Please note the changed default behavior of the CLI script options. They are all set to "false" now by default.

**Comment by llauner** [comment]
OK, I've just given it a try, it's now exiting with the correct exit code, but it looks like it's not printing anything on the output anymore ?
I think it's still usefull to know why validation failed or have the information it used to display...

**Comment by reskume** [comment]
use it with the debug flag -D. does this work?Am 12.11.2022 um 17:51 schrieb Ludovic ***@***.***>:﻿
OK, I've just given it a try, it's now exiting with the correct exit code, but it looks like it's not printing anything on the output anymore ?
I think it's still usefull to know why validation failed or have the information it used to display...

**Comment by llauner** [comment]
Yes...it's' fine now, sorry I didn't see the --debug option.
Thanks !
