### ISSUE TITLE
Token 'AL' on line 155 does not allow subsequent token 'AF' 

### ISSUE THREAD

**Issue by llauner** [openAIP/openaip-openair-parser#31]
Hi
Have you changed anything in the file validation ?
I'm getting this error which I think wasn't there in the past:
Error found at line 156: Token 'AL' on line 155 does not allow subsequent token 'AF' on line 156

Where should AF be located then ?
It's going to be tough if I have to relocate the AF line somewhere else...
Thanks

**Comment by reskume** [comment]
I haven’t changed anything in a while. I’ll have look into this asap. Should be an easy fix. Am 07.04.2023 um 15:26 schrieb Ludovic ***@***.***>:﻿
Hi
Have you changed anything in the file validation ?
I'm getting this error which I think wasn't there in the past:
Error found at line 156: Token 'AL' on line 155 does not allow subsequent token 'AF' on line 156
Where should AF be located then ?
It's going to be tough if I have to relocate the AF line somewhere else...
Thanks

**Comment by llauner** [comment]
Hi
I'm getting another similar error:
Error found at line 14167: Token 'DC' on line 14166 does not allow subsequent token 'DY' on line 14167
