### ISSUE TITLE
Token 'DC' on line 14166 does not allow subsequent token 'DY'

### ISSUE THREAD

**Issue by llauner** [openAIP/openaip-openair-parser#32]
Hi
I'm getting another similar error:
Error found at line 14167: Token 'DC' on line 14166 does not allow subsequent token 'DY' on line 14167

_Originally posted by @llauner in https://github.com/openAIP/openaip-openair-parser/issues/31#issuecomment-1508075211_

**Comment by reskume** [comment]
It's nearly impossible to help without an example openair or link to the file that caused the issue. From the error message alone, this seems legit and "works as expected". A definition of a circular airspace (currently the only place where openair parser allows token sequence "V X" -> "DC") cannot have an appended airway definition.

```text/plain
AC R
AN ED-R3 Geesthacht H24
AH 2200ft MSL
AL GND
V X=53:24:25 N 010:25:10 E
DC 1.10
```

**Comment by llauner** [comment]
Find example file attached
[france-2023-fixed.txt](https://github.com/openAIP/openaip-openair-parser/files/11230894/france-2023-fixed.txt)

**Comment by reskume** [comment]
I get the error:

`Error found at line 13528: Token 'DC' on line 13527 does not allow subsequent token 'DY' on line 13528`

Which correctly identifies an error in this exact line. See the complete definition block attached:

```
AC P
AN Axe 3
AL FL090
AH FL140
V X=44:13:00 N 005:08:00 E
DC 0.5
DY 44:13:00 N 005:08:00 E
```

**Comment by llauner** [comment]
OK, perfect.
Thanks

**Comment by reskume** [comment]
I assume I can close the ticket?

**Comment by llauner** [comment]
Yes, I closed it. Thanks
