### ISSUE TITLE
Update documenation for extended format

### ISSUE THREAD

**Issue by llauner** [openAIP/openaip-openair-parser#35]
Hi
Might not be the best place to discuss this, but I didn't know how to reach you:

In the[ openaip format,](http://www.winpilot.com/usersguide/userairspace.asp):
1) The AY tag does not seem to support the value: AERIAL_SPORTING_RECREATIONAL
In reality it seems to be OK

2) AY GLIDING_SECTOR should be AY W
If not, SeeYou, doesn't recognize it.

With the incorrect AY value, SeeYou displays the area as "unclassified" which leads to lots of grey areas on the map

Do you have any link to a more up to date version of the format ?
Could you make sure that your parser / converter to the extended format are in line with what is currently supported by SeeYou, ...

**Comment by reskume** [comment]
The values used are the ones that we use for openaip. We decided to have verbose values instead of shorthand abbreviations. I don't have a link to a "newer" version of the format. The one I posted is the "official" one. 

Personally I think the format is outdated because of so many things and it should be avoided at all costs. Newer formats, be it the openaip JSON or GeoJSON or AIXM are way way better than openair since there are tools to parse and validate the content. In case of GeoJSON, you are even able to import and edit the geometries in a GIS like QGIS. 

Regarding the types, it may be a good idea to ask Naviter et al if they can extended the list of "known" airspaces types on their side.

**Comment by llauner** [comment]
We've moved to the extended format following your recommendations, and now you're saying that OpenAir is not even the right file format ?
Do you know if OpenAIP JOSN or other mentioned formats are supported by SeeYou, SeeYou Navigator and XCSoar ?

**Comment by reskume** [comment]
To clarify: this is my **personal** opinion on this format. It lacks so many things, starting from a valid definition/schema that it can be validated against. Not to mention e.g. multiple frequencies and ground stations, activation period for an airspace  - the list goes on. It's abused and interpreted in so many ways that you have **different** versions for e.g. SeeYou and XCSoar  - e.g. see the AustroControl offering. This is all a freaking mess! 

What we do with our hardware: we simply use the openaip JSON format that comes with a JSON schema that is documented and includes tools to easily validate a JSON payloads against the documentd schema to check if the data is correct. We don't care about openair. Where openair really **shines** (and that is, I assume, historical the reason) that you can very easily "port" written AIP definitions into machine-readable text. Those definitions are also smaller in size (e.g. circle definitions) than e.g. GeoJSON definitions which may have been a problem for older systems that cannot handle so massive polygon points.

Our plan is also to add an "AIP text parser" to openaip that allows simply copying written text to a textfield and get valid openaip GeoJSON/JSON in return. That's our way forward to maintain airspace data.

Moving to the extended format is the best way to go forward (if you want to stick with openAIR) as it adds a bit more metadata on each airspace - in my opinion this should be the de-facto standard when dealing with openair. Nonetheless, it's still mediocre compared to openAIP JSON or AIXM.

Metadata transported **extended OpenAIR**:

- Type
- ICAO Class
- Ceiling High
- Ceiling Low
- Ground Station Frequency
- Ground Station Call-Sign
- Geometry

Metadata transported with **OpenAIP JSON** (which must validate against a given schema to be valid):

- Type
- ICAO Class
- Activity
- On Demand Flag
- On Request Flag
- By NOTAM Flag
- Special Agreement Flag
- Request Compliance Flag
- Country
- Upper Limt
- Lower Limit
- Upper Limit Max
- Lower Limit Max
- Geometry
- Active From
- Active Until
- Hours Of Operation
- Remarks

Compared to AIXM, the openaip format is very simple but it transports the most useful metadata and is easily parseable and extendable.

One **big** downside when it comes to those formats is that you require a tool to create the actual data, for example the openAIP airspace editor that let's you input openair airspace definition taken from the AIP and then add more metadata. It cannot be easily edited within a text editor unless you know what you are doing.
