### ISSUE TITLE
Ignore invalid airspaces

### ISSUE THREAD

**Issue by Wackymax** [openAIP/openaip-openair-parser#6]
Hi, really awesome lib. Thank you so much for creating and maintaining this!

Would it be possible to get a flag to skip over invalid airspaces rather than breaking the entire parsing process?

**Comment by reskume** [comment]
The parser is configured to be strict by default, i.e. it will throw an error if an invalid airspace is encountered during parsing. In addition to the strict behavior, there is also the "fixGeometry" which will try to fix invalid airspaces and keep their geometry. Is this what you are looking for perhaps? Or do you really want to drop invalid airspace completely?

**Comment by Wackymax** [comment]
I would like to ignore invalid airspaces. Possibly just have it in array for querying to see which ones were invalid. I managed to work around my issue though, it seems like there is another bug that I stumbled upon in this file https://soaringweb.org/Airspace/NA/allusa.v21.08-12.5.txt where it parses correctly if unit conversion is set to ft but if I set the target unit to be m then it fails to parse the file with an error. So for now I will parse the file in ft and then convert to m afterwards but maybe something to look at?

**Comment by Wackymax** [comment]
Thank you for the speedy fix!

**Comment by reskume** [comment]
The issue with unit conversion is fixed in the new release. I'll have to look into how to ignore invalid airspaces and have them in an array for review. But this will take some time though since I assume that this will be a bigger rewrite.

**Comment by reskume** [comment]
You closed this intentionally or is the "skip invalid airspaces" flag still requested? :)

**Comment by Wackymax** [comment]
For now my immediate issue is addressed. Let's leave the skip functionality for now. Thank you Stephan!
